[registry_hosts]
#Liste des IP
35.180.113.167

[registry_hosts:vars]
#Variable commune à tout les hotes du groupe
ansible_user=ubuntu
ansible_ssh_private_key_file=~/registry-key.pem
#On désactive la vérification de la clé hote pour éviter le prompt (Yes/No)
ansible_ssh_common_args = -o StrictHostKeyChecking=no
